### ISSUE TITLE
Installation of BSDE: Barycenter package is archived and Issues with installation afterwards

### ISSUE THREAD

**Issue by qz91** [mqzhanglab/BSDE#3]
Hi, I'm having trouble installing BSDE after ensuring all other dependencies are satisfied. I observed that Barycenter package, which is an R requisite dependency of your package, is archived. As such, I downloaded the archived version locally.

Yet, I'm still running into issues downloading this package. Here is the issue:

```
✔  checking for file ‘/private/var/folders/pk/00p956hd3ylgq_kncnv3pgb80000gp/T/RtmpS730cR/remotes38d963555f35/mqzhanglab-BSDE-58b31cf/DESCRIPTION’ ...
─  preparing ‘BSDE’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘BSDE’ ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   *** installing help indices
   ** building package indices
   ** installing vignettes
   ** testing if installed package can be loaded from temporary location
   Error: package or namespace load failed for ‘BSDE’:
    .onLoad failed in loadNamespace() for 'BSDE', details:
     call: NULL
     error: /Users/MYNAME/opt/anaconda3/envs/r-reticulate/lib/libpython3.10.dylib - dlopen(/Users/MYNAME/opt/anaconda3/envs/r-reticulate/lib/libpython3.10.dylib, 0x000A): tried: '/Users/MYNAME/opt/anaconda3/envs/r-reticulate/lib/libpython3.10.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/MYNAME/opt/anaconda3/envs/r-reticulate/lib/libpython3.10.dylib' (no such file), '/Users/MYNAME/opt/anaconda3/envs/r-reticulate/lib/libpython3.10.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
   Error: loading failed
   Execution halted
   ERROR: loading failed
─  removing ‘/private/var/folders/pk/00p956hd3ylgq_kncnv3pgb80000gp/T/RtmpWyd3A7/Rinst3a3024b93283/BSDE’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'BSDE' from GitHub:
  ! System command 'R' failed
In addition: Warning message:
In readLines(old_path) :
  incomplete final line found on '/Users/MYNAME/.R/Makevars'
```

I'm not sure what to make of this error, as I ensured I also have `r-reticulate` with a Python version of 3.10. How would I go about troubleshooting this and downloading the BSDE package?

Thank you so much in advance. I look forward to hearing back from you.

**Comment by richardkwo** [comment]
> mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')

From the error log, it seems due to installing a x86 binary on an ARM/apple silicon machine. Please make sure to install the right binary.

**Comment by qz91** [comment]
Would this mean that I would have to install this arm64 binary within the r-reticulate environment or globally? If so, I saw that I have an arm architecture already, so wouldn't I have an arm64 binary by default? I checked this by typing 
```
$arch
```

and it returned `arm64`.  For context, I am using a macbook with an M1 chip. I would have assumed that I had an arm64 already, so I'm not sure why it says I have an x86_64 binary.

**Comment by richardkwo** [comment]
Yes, I think you installed the wrong arch for r-reticulate. See also: https://stackoverflow.com/questions/72308682/mach-o-file-but-is-an-incompatible-architecture-have-x86-64-need-arm64e

Once you got that fixed, you should be able to install BSDE.

**Comment by qz91** [comment]
Thanks for bearing with me. I was able to somehow reconfigure this. However, now it says my scipy version is broken and that we cannot import "show_config" from numpy, despite reinstalling it multiple times. Does BSDE work with Scipy version 1.11 and Numpy 1.25 or does it only work for Scipy 1.7? Also, my reticulate uses Python 3.10. Do we absolutely need Python 3.7 as your vignette has in your virtual environment?

Here's the output when I try to install BSDE via `devtools::install_github("mqzhanglab/BSDE", build_vignettes = TRUE)`:

```
── R CMD build ──────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/pk/00p956hd3ylgq_kncnv3pgb80000gp/T/RtmpCVk8Yf/remotesceb2666d430a/mqzhanglab-BSDE-58b31cf/DESCRIPTION’ ...
─  preparing ‘BSDE’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘BSDE’ ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   *** installing help indices
   ** building package indices
   ** installing vignettes
   ** testing if installed package can be loaded from temporary location
   Error: package or namespace load failed for ‘BSDE’:
    .onLoad failed in loadNamespace() for 'BSDE', details:
     call: py_run_file_impl(file, local, convert)
     error: ImportError: cannot import name 'show_config' from 'numpy' (unknown location)
   Run `reticulate::py_last_error()` for details.
   Error: loading failed
   Execution halted
   ERROR: loading failed
─  removing ‘/private/var/folders/pk/00p956hd3ylgq_kncnv3pgb80000gp/T/RtmphbEesn/Rinstd3415378017b/BSDE’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'BSDE' from GitHub:
  ! System command 'R' failed
In addition: Warning message:
In readLines(old_path) :
  incomplete final line found on '/Users/zaqian/.R/Makevars'
```

**Comment by richardkwo** [comment]
These should not be a problem, as long as `reticulate' works. 

Can you run `reticulate::py_last_error()`?

**Comment by qz91** [comment]
Yes, when I run this, it just returns `NULL`, however.

**Comment by richardkwo** [comment]
I am afraid I am unable to reproduce it... I would suggest to double check that you can run reticulate properly on R, and that the python environ that reticulate talks to has [POT](https://pythonot.github.io/) properly installed. For example, try calling POT with reticulate in R.
